name: Project Publishing
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths: [ 'Avalonia.FluentUI/**', '**/Publish.yml' ]
jobs:
  publish:
    strategy:
      matrix:
        include:
          - platform: windows-latest
            runtime: win-x64
          - platform: ubuntu-latest
            runtime: linux-x64
          - platform: macos-latest
            runtime: osx-x64
          - platform: macos-latest
            runtime: osx-arm64
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            Avalonia.FluentUI
            Avalonia.FluentUI.slnx
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-cache-${{ matrix.runtime }}
      - run: dotnet publish -r ${{ matrix.runtime }}
      - uses: actions/upload-artifact@v5
        with:
          name: Release-${{ matrix.runtime }}
          path: |
            **/publish
            !**/*.pdb
            !**/*.dbg
            !**/*.dSYM