name: Project Publishing
permissions:
  contents: read
on:
  push:
    paths: [ 'Avalonia.FluentUI/**', '**/Publish.yml' ]
jobs:
  publish:
    strategy:
      matrix:
        include:
          - platform: windows-latest
            runtime: win-x64
          - platform: ubuntu-latest
            runtime: linux-x64
          - platform: macos-latest
            runtime: osx-x64
          - platform: macos-latest
            runtime: osx-arm64
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          cache: true
          dotnet-version: '10.x'
          cache-dependency-path: '**/*.csproj'
      - run: dotnet publish -r ${{ matrix.runtime }} -p:PublishAot=true -p:OptimizationPreference=Speed -p:DebugSymbols=false
      - if: matrix.platform == 'macos-latest'
        working-directory: 'Avalonia.FluentUI/bin/Release/net10.0/${{ matrix.runtime }}/publish'
        run: |
          chmod +x Avalonia.FluentUI.app/Contents/MacOS/Avalonia.FluentUI
          codesign --force --deep --sign - Avalonia.FluentUI.app
      - uses: actions/upload-artifact@v5
        with:
          name: Release-${{ matrix.runtime }}
          path: |
            ${{ matrix.platform == 'macos-latest' && '**/*.app' || '**/publish' }}
            !**/*.dSYM