name: Project Publishing
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths: [ 'Avalonia.FluentUI/**', '**/Publish.yml' ]
jobs:
  publish:
    strategy:
      matrix:
        include:
          - platform: windows-latest
            runtime: win-x64
          - platform: windows-latest
            runtime: win-arm64
          - platform: macos-latest
            runtime: osx-x64
          - platform: macos-latest
            runtime: osx-arm64
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-cache-${{ matrix.runtime }}
      - run: dotnet publish -r ${{ matrix.runtime }} -p:PublishAot=true -p:InvariantGlobalization=true -p:IlcFoldIdenticalMethodBodies=true  -p:OptimizationPreference=Size
      - if: matrix.platform == 'macos-latest'
        working-directory: 'Avalonia.FluentUI/bin/Release/net10.0/${{ matrix.runtime }}/publish'
        run: |
          chmod +x Avalonia.FluentUI.app/Contents/MacOS/Avalonia.FluentUI
          codesign --force --deep --sign - Avalonia.FluentUI.app
          hdiutil create -volname "Avalonia.FluentUI" -srcfolder Avalonia.FluentUI.app -ov -format UDZO Avalonia.FluentUI.dmg
      - uses: actions/upload-artifact@v5
        with:
          name: Release-${{ matrix.runtime }}
          path: |
            ${{ matrix.platform == 'macos-latest' && '**/*.dmg' || '**/publish' }}
            !**/*.pdb
            !**/*.dbg
            !**/*.dSYM